language: node_js
node_js:
- '0.12'
before_script:
  - npm install -g bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - cat ./coverage/lcov/lcov.info | node_modules/.bin/coveralls

